" Enable filetype plugins
filetype plugin indent on
" Enable syntax highlighting
syntax on
" Use spaces instead of tabs
set expandtab
" Set indentation depth to 2 spaces
set shiftwidth=2
set tabstop=2
" Show line numbers
set number
" Show matching brackets
set showmatch
" Automatically indent based on filetype
set autoindent
" Unset Highlight search results
set nohlsearch
" Set no backup
set nobackup
" Show white space
set list
set listchars=tab:→\ ,trail:·
" Set scrolloff for zt, zb
set scrolloff=5
" For consistent with tmux interface
nnoremap <C-b> <C-w>
" Use Space as the easymotion leader
map <Space> <Plug>(easymotion-prefix)
" Set auto pairs
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
call plug#begin('~/.vim/plugged')
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-commentary'
Plug 'easymotion/vim-easymotion'
Plug 'tpope/vim-surround'
call plug#end()
